session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  login: admin
  password: admin
database:
  host: tg-postgres
  port: 5432
  user: user_pg
  password: user_pass
  database: smarties_game
bot:
  token: 5579588003:AAGwGPrSsXtiXuIbiNb-cxYCUr5Vo9jScMg
  id: 5579588003
rabbitmq:
  queue_name: smart_bot
  rabbit_url: amqp://user_mq:pass_mq@tg-rabbitmq:5672/
game:
  theme_id: -1
  time_for_game: 5
  time_for_answer: 15
  difficulty_levels:
    1:
      color: "Зеленая дорожка"
      max_questions: 4
      max_mistakes: 2
    2:
      color: "Желтая дорожка"
      max_questions: 3
      max_mistakes: 1
    3:
      color: "Красная дорожка"
      max_questions: 2
      max_mistakes: 0





