session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  login: admin
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: user_pg
  password: user_pass
  database: smarties_game
game:
  theme_id: -1
  time_for_game: 5
  time_for_answer: 15
  difficulty_levels:
    1:
      color: "green"
      max_question: 4
      max_mistakes: 2
    2:
      color: "yellow"
      max_question: 3
      max_mistakes: 1
    3:
      color: "red"
      max_question: 2
      max_mistakes: 0





