"""replace is_master to is_answering

Revision ID: 41755da54473
Revises: c99b359fb7d4
Create Date: 2022-09-14 23:32:58.114542user_pass

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41755da54473'
down_revision = 'c99b359fb7d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_progress', sa.Column('is_answering', sa.BOOLEAN(), nullable=True))
    op.drop_column('game_progress', 'is_master')
    op.drop_constraint('game_sessions_id_answering_gamer_fkey', 'game_sessions', type_='foreignkey')
    op.drop_column('game_sessions', 'id_answering_gamer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('id_answering_gamer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_sessions_id_answering_gamer_fkey', 'game_sessions', 'gamers', ['id_answering_gamer'], ['id'])
    op.add_column('game_progress', sa.Column('is_master', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('game_progress', 'is_answering')
    # ### end Alembic commands ###
