"""Add default start time

Revision ID: 5dab01d10168
Revises: 8c2bb5469db4
Create Date: 2022-09-21 13:17:20.998082user_pass

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dab01d10168'
down_revision = '8c2bb5469db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
