"""Add is_master to GP

Revision ID: ac3389e30ebb
Revises: 5370a1b7b468
Create Date: 2022-09-13 11:37:13.073727user_pass

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3389e30ebb'
down_revision = '5370a1b7b468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_progress', sa.Column('is_master', sa.BOOLEAN(), nullable=True))
    op.drop_column('gamers', 'is_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamers', sa.Column('is_master', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('game_progress', 'is_master')
    # ### end Alembic commands ###
