"""try fix relationship

Revision ID: c99b359fb7d4
Revises: bd561c3fdb42
Create Date: 2022-09-14 23:17:51.986382user_pass

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99b359fb7d4'
down_revision = 'bd561c3fdb42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
