session:
  key: 
admin:
  login: 
  password: 
database:
  host: tg-postgres
  port: 5432
  user: 
  password: 
  database: smarties_game
bot:
  token: 
  id: 
rabbitmq:
  queue_name: smart_bot
  rabbit_url: 
game:
  theme_id: -1
  time_for_game: 5
  time_for_answer: 15
  difficulty_levels:
    1:
      color: "Зеленая дорожка"
      max_questions: 4
      max_mistakes: 2
    2:
      color: "Желтая дорожка"
      max_questions: 3
      max_mistakes: 1
    3:
      color: "Красная дорожка"
      max_questions: 2
      max_mistakes: 0





